# Generated by Django 3.2.1 on 2022-04-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='student.student'),
        ),
        migrations.AddField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='employer.job'),
        ),
    ]
